### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by tsinis** [fujidaiti/dart-package-inspector#38]
Hey @fujidaiti!

First of all - thanks for the great action! This is just a friendly reminder that, as the title and [GitHub Changelog](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20) say (so as warnings in our CIs) - `Node.js 16 actions are deprecated` :). Thanks again!

**Comment by fujidaiti** [comment]
Hi. This fix has been released in v2.0.0. Please update the action's version in your workflow.

```
- uses: fujidaiti/dart-package-inspector@v2
```
